### ISSUE TITLE
Fix capitalization for brands and tags in samples

### ISSUE THREAD

**Issue by Prakash-Sundaresan** [DefangLabs/defang-docs#66]
Can we pay attention to capitalization in our samples READMEs - they should align with brand guidelines for the respective brands. For example, in [this sample](https://github.com/DefangLabs/samples/blob/main/samples/langchain/README.md), it should be “Flask” not “flask” and “LangChain” not “Langchain”. It might appear to be a small thing but it makes us look unprofessional.

Also, , the tags in the samples need to be consistent in the capitalization - currently they seem all over the place. Sometimes it is “flask”, sometimes “Flask”. And “Langchain & Flask & AI” is clearly wrong, I think the tags should have a comma in between, not “&”.

![Image](https://github.com/user-attachments/assets/a9893843-a156-4688-ac28-c91f234505c8)
![Image](https://github.com/user-attachments/assets/9aa1c275-abe6-4aa4-9577-e5faf35ccafa)

**Comment by Prakash-Sundaresan** [comment]
@Chrisyhjiang - I believe this already fixed. Please can you link to the corresponding PR(s) and close this?

**Comment by Chrisyhjiang** [comment]
https://github.com/DefangLabs/samples/pull/149

This is the normalization pr that fixes this issue.

**Comment by Chrisyhjiang** [comment]
fixed by #https://github.com/DefangLabs/samples/pull/149
